add DdTags
schubergphilis/terraform-aws-mcaf-datadog pull request #11
Opened 2021-03-25 10:35 UTC by banovicn

2021-03-25 12:05 UTC, svanharmelen commented on main.tf
>      DdSite            = var.site_url
Keep it ordered 😉 

```suggestion
    DdSite            = var.site_url
    DdTags            = var.datadog_tags
```

2021-04-08 06:38 UTC, marwinbaumannsbp approved these changes

2021-04-08 06:55 UTC, marwinbaumannsbp requested changes

2021-04-08 06:55 UTC, marwinbaumannsbp commented on main.tf
> +    DdTags            = var.datadog_tags
DdTags must be a string but the datadog_tags variable is a list(string). Can you transform this variable into a string?

2021-04-08 10:29 UTC, marwinbaumannsbp approved these changes

2021-04-08 10:45 UTC, merged